// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Perimeter.Gateway.Infrastructure.PlatformStore;

#nullable disable

namespace Perimeter.Gateway.Infrastructure.PlatformStore.Migrations
{
    [DbContext(typeof(PlatformStoreDbContext))]
    [Migration("20260828191007_InitialPlatformStore")]
    partial class InitialPlatformStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pdg")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ActorCapabilityEntity", b =>
                {
                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("Capability")
                        .HasColumnType("text")
                        .HasColumnName("capability");

                    b.HasKey("ActorId", "Capability");

                    b.ToTable("actor_capability", "pdg");
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ActorEntity", b =>
                {
                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.HasKey("ActorId");

                    b.ToTable("actor", "pdg");
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.AuditRecordEntity", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditId"));

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capability");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("EffectiveRowScope")
                        .HasColumnType("jsonb")
                        .HasColumnName("effective_row_scope");

                    b.Property<string>("NormalizedParameters")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_parameters")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_category");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<int>("RowsReturned")
                        .HasColumnType("integer")
                        .HasColumnName("rows_returned");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.HasKey("AuditId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_record_occurred_at");

                    b.HasIndex("SubjectId", "ActorId")
                        .HasDatabaseName("ix_audit_record_subject_actor");

                    b.ToTable("audit_record", "pdg", t =>
                        {
                            t.HasCheckConstraint("ck_audit_record_decision", "decision IN ('ALLOW', 'DENY')");

                            t.HasCheckConstraint("ck_audit_record_deny_rows_returned", "decision = 'ALLOW' OR rows_returned = 0");

                            t.HasCheckConstraint("ck_audit_record_rows_returned", "rows_returned >= 0");
                        });
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.DelegationEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("SubjectId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("delegation", "pdg");
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceEntity", b =>
                {
                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<int>("MaxRows")
                        .HasColumnType("integer")
                        .HasColumnName("max_rows");

                    b.Property<string>("RequiredCapability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_capability");

                    b.HasKey("ResourceName");

                    b.ToTable("resource", "pdg", t =>
                        {
                            t.HasCheckConstraint("ck_resource_max_rows", "max_rows > 0");
                        });
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceOutputFieldEntity", b =>
                {
                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("ResourceName", "FieldName");

                    b.HasAlternateKey("ResourceName", "Ordinal");

                    b.ToTable("resource_output_field", "pdg", t =>
                        {
                            t.HasCheckConstraint("ck_resource_output_field_ordinal", "ordinal > 0");
                        });
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceParameterEntity", b =>
                {
                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<string>("ParamName")
                        .HasColumnType("text")
                        .HasColumnName("param_name");

                    b.Property<string>("ParamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("param_type");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.HasKey("ResourceName", "ParamName");

                    b.ToTable("resource_parameter", "pdg");
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.HasKey("SubjectId");

                    b.ToTable("subject", "pdg");
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectResourcePermissionEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean")
                        .HasColumnName("allowed");

                    b.Property<string>("RowScopeMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("row_scope_mode");

                    b.HasKey("SubjectId", "ResourceName");

                    b.HasIndex("ResourceName");

                    b.ToTable("subject_resource_permission", "pdg", t =>
                        {
                            t.HasCheckConstraint("ck_subject_resource_permission_row_scope_mode", "row_scope_mode IN ('ALL', 'ALLOW_LIST')");
                        });
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectRowScopeEntity", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text")
                        .HasColumnName("resource_name");

                    b.Property<string>("Dimension")
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<string>("AllowedValue")
                        .HasColumnType("text")
                        .HasColumnName("allowed_value");

                    b.HasKey("SubjectId", "ResourceName", "Dimension", "AllowedValue");

                    b.ToTable("subject_row_scope", "pdg");
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ActorCapabilityEntity", b =>
                {
                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ActorEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.DelegationEntity", b =>
                {
                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ActorEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceOutputFieldEntity", b =>
                {
                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceEntity", null)
                        .WithMany()
                        .HasForeignKey("ResourceName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceParameterEntity", b =>
                {
                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceEntity", null)
                        .WithMany()
                        .HasForeignKey("ResourceName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectResourcePermissionEntity", b =>
                {
                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.ResourceEntity", null)
                        .WithMany()
                        .HasForeignKey("ResourceName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectRowScopeEntity", b =>
                {
                    b.HasOne("Perimeter.Gateway.Infrastructure.PlatformStore.Entities.SubjectResourcePermissionEntity", null)
                        .WithMany()
                        .HasForeignKey("SubjectId", "ResourceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
